language: go

go:
  - 1.4

script: go test -v ./...

notifications:
  email:
    on_success: change
    on_failure: always

deploy:
  provider:
    provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: jamesclonk@jamesclonk.ch
  password:
    secure: ihEjAI9xcW2/sH+2Y7nweyDWksgKZ7BDx6BN5lDGC5LwsWvSWfa/O2JmzCn02eUKPvsbaVxIlSyJvNBaP7MSy/oBVbgMQqEDDjJcaixMOx1xBfslt6+WhuPCCBeYK5ZGsQnsKetPnNRDi9kUuTUbtPTU/oHHg6HLUrr1Ec5ymqk1IfiRdy44kd4Xbq3XtzBbyXnfAO1HW9/iL/ve6OYw0G3T5xcThHqWHRF161+o8vOAVRdiV4uuIA9MgknS/bDwpkT95rlHeOlkWotNvVK6TuBUTA0BNUmZ05uyxiS5Zn3MVEMDxwzP8Vhbqye76Qie9RavjRJt5zBj3Ah0Y6qqOsxaLmDuf2Gz0jIXtREfXmywmTeoAUrP2vbML9hC2IOT3KW3yC00cLgGd/qBE4//s3EcIIjg6cHPgPO8M3ZAIpnDFQI3hdil4s6oDCSfWgBhTEVkkxc8ovOhq5qtLXbvqlbqZMI9venRslujvVg1cwG3A7wQib+RX+ZtWFMIJDXaULNTuR4Yue1EcjrOJ5hyoJ68RMqzq2VNmwsDpaQhMtuY4qlg5lAoVdhlmwijWH7a64ZYln5qM9lra8i8nnaJus0wE3EozTeLrLyCRXGwHv/ARi1E+eJ6CmGyZRBVrgNk7BOHHw1PeAPR8GSVnl2lVsLGkvze4ya8EFsEYT71mnE=
  organization: jamesclonk.io
  space: development
  on:
    branch: master
